2025-09-23 13:34:09,609 - INFO - _internal - 127.0.0.1 - - [23/Sep/2025 13:34:09] "GET /apidocs/ HTTP/1.1" 200 -
2025-09-23 13:34:09,954 - INFO - _internal - 127.0.0.1 - - [23/Sep/2025 13:34:09] "GET /flasgger_static/swagger-ui.css HTTP/1.1" 200 -
2025-09-23 13:34:09,967 - INFO - _internal - 127.0.0.1 - - [23/Sep/2025 13:34:09] "GET /flasgger_static/lib/jquery.min.js HTTP/1.1" 200 -
2025-09-23 13:34:09,981 - INFO - _internal - 127.0.0.1 - - [23/Sep/2025 13:34:09] "GET /flasgger_static/swagger-ui-bundle.js HTTP/1.1" 200 -
2025-09-23 13:34:09,981 - INFO - _internal - 127.0.0.1 - - [23/Sep/2025 13:34:09] "GET /flasgger_static/swagger-ui-standalone-preset.js HTTP/1.1" 200 -
2025-09-23 13:34:10,177 - INFO - _internal - 127.0.0.1 - - [23/Sep/2025 13:34:10] "GET /apispec_1.json HTTP/1.1" 200 -
2025-09-23 13:34:10,187 - INFO - _internal - 127.0.0.1 - - [23/Sep/2025 13:34:10] "GET /flasgger_static/favicon-32x32.png HTTP/1.1" 200 -
2025-09-23 13:34:32,498 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 13:34:42,517 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000012067472CC0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:23:10,370 - INFO - ana - Veritabaný altyapýsý kontrol edildi ve hazýr.
2025-09-23 14:23:10,370 - INFO - ana - RVM Sistemi 4321 portunda baþlatýlýyor...
2025-09-23 14:23:10,371 - INFO - ana - Heartbeat döngüsü baþladý. Ýlk gönderim 60 saniye sonra yapýlacak.
2025-09-23 14:23:10,371 - INFO - ana - Arka plan heartbeat servisi baþlatýldý.
2025-09-23 14:23:11,733 - INFO - _internal - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:4321
 * Running on http://192.168.53.105:4321
2025-09-23 14:23:11,734 - INFO - _internal - [33mPress CTRL+C to quit[0m
2025-09-23 14:24:10,373 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:24:20,387 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CEED0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:25:20,387 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:25:30,391 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CF3B0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:26:30,392 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:26:40,393 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CEEA0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:27:40,394 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:27:50,407 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CFB30>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:28:50,409 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:29:00,420 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FC2F0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:30:00,421 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:30:10,427 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FCA70>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:31:10,429 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:31:20,434 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CFAD0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:32:20,435 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:32:30,440 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CDAC0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:33:30,442 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:33:40,446 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FCC50>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:34:40,448 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:34:50,462 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FC3B0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:35:50,463 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:36:00,475 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FDA00>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:37:00,477 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:37:10,485 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FE2D0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:38:10,487 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:38:20,504 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CE1E0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:39:20,505 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:39:30,517 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CFC50>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:40:30,518 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:40:40,524 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FDC40>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:41:40,526 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:41:50,536 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FC050>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:42:50,537 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:43:00,551 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FCBF0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:44:00,552 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:44:10,559 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FD400>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:45:10,560 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:45:20,562 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CFE60>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:46:20,563 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:46:30,566 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CDA00>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:47:30,568 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:47:40,571 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FCA70>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:48:40,572 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:48:50,582 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FC2F0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:49:50,583 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:50:00,599 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FD9D0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:51:00,600 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:51:10,606 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FE2D0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:52:10,607 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:52:20,609 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CDA00>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:53:20,611 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:53:30,625 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CF980>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:54:30,626 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:54:40,640 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FDFA0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:55:40,641 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:55:50,651 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FD820>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:56:50,653 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:57:00,661 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FCD10>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:58:00,662 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:58:10,665 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FD040>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 14:59:10,666 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 14:59:20,682 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CFCB0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:00:20,683 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:00:30,698 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CDA00>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:01:30,699 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:01:40,703 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FCF20>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:02:40,704 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:02:50,718 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FC800>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:03:50,719 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:04:00,730 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FD910>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:05:00,731 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:05:10,735 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FE240>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:06:10,736 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:06:20,753 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CFB60>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:07:20,754 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:07:30,770 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CFA40>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:08:30,771 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:08:40,776 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FE150>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:09:40,778 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:09:50,784 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FD820>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:10:50,785 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:11:00,792 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FCD10>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:12:00,794 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:12:10,797 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FC8C0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:13:10,798 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:13:20,807 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CD6D0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:14:20,808 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:14:30,820 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CE360>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:15:30,821 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:15:40,826 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FCA40>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:16:40,827 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:16:50,829 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FC410>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:17:50,830 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:18:00,844 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FD670>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:19:00,845 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:19:10,850 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FD7C0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:20:10,852 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:20:20,854 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CEED0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:21:20,855 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:21:30,860 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CEE40>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:22:30,861 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:22:40,876 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FE0F0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:23:40,878 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:23:50,894 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FD9D0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:24:50,896 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:25:00,908 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FC1A0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:26:00,910 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:26:10,922 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FCD40>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:27:10,923 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:27:20,939 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CFF80>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:28:20,940 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:28:30,944 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CFE30>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:29:30,945 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:29:40,948 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CF2C0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:30:40,950 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:30:50,953 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FD430>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:31:50,953 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:32:00,964 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FC470>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:33:00,966 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:33:10,969 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FC740>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:34:10,971 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:34:20,982 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CF380>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:35:20,983 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:35:30,987 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CF920>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:36:30,989 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:36:41,001 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CEE10>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:37:41,002 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:37:51,009 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FD5B0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:38:51,011 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:39:01,016 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FC200>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:40:01,018 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:40:11,033 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FD2B0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:41:11,034 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:41:21,036 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CDAF0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:42:21,037 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:42:31,050 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CF260>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:43:31,052 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:43:41,063 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CF590>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:44:41,065 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:44:51,075 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FC560>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:45:51,076 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:46:01,090 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FC7D0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:47:01,091 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:47:11,096 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FDA90>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:48:11,097 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:48:21,109 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CFE00>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:49:21,111 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:49:31,122 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CFC50>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:50:31,124 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:50:41,136 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CEDE0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:51:41,137 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:51:51,145 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FC260>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:52:51,146 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:53:01,159 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FC830>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:54:01,161 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:54:11,172 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FCB90>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:55:11,173 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:55:21,174 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CFB60>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:56:21,175 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:56:31,180 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CFC20>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:57:31,182 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:57:41,186 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CF560>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:58:41,188 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 15:58:51,200 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FC3E0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 15:59:51,201 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:00:01,203 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FC980>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 16:01:01,204 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:01:11,214 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FC170>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 16:02:11,216 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:02:21,219 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CFAD0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 16:03:21,221 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:03:21,761 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:04:21,763 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:04:31,766 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CF650>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 16:05:31,768 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:05:41,774 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CE510>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 16:06:41,775 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:06:51,782 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FC1D0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 16:07:51,783 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:08:01,795 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FC2F0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 16:09:01,797 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:09:11,813 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FD280>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 16:10:11,815 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:10:21,832 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CE5A0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 16:11:21,834 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:11:31,838 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CF0E0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 16:12:31,840 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:12:41,847 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CF8C0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 16:13:41,848 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:13:51,849 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FCB00>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 16:14:51,850 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:15:01,861 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FC3B0>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 16:16:01,862 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:16:11,868 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FC110>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 16:17:11,870 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:17:21,883 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CED50>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 16:18:21,884 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:18:31,900 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CFA40>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 16:19:31,901 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:19:41,904 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090CEF60>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 16:20:41,906 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:20:42,071 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:21:42,074 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:21:42,125 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:22:42,131 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:22:42,181 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:23:42,186 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:23:42,239 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:24:42,240 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:24:42,288 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:25:42,293 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:25:42,358 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:26:42,364 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:26:42,413 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:27:05,274 - INFO - ana - Veritabaný altyapýsý kontrol edildi ve hazýr.
2025-09-23 16:27:05,274 - INFO - ana - RVM Sistemi 4321 portunda baþlatýlýyor...
2025-09-23 16:27:05,274 - INFO - ana - Heartbeat döngüsü baþladý. Ýlk gönderim 60 saniye sonra yapýlacak.
2025-09-23 16:27:05,274 - INFO - ana - Arka plan heartbeat servisi baþlatýldý.
2025-09-23 16:27:05,322 - INFO - _internal - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:4321
 * Running on http://192.168.53.105:4321
2025-09-23 16:27:05,322 - INFO - _internal - [33mPress CTRL+C to quit[0m
2025-09-23 16:27:42,414 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:27:42,479 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:28:05,278 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:28:05,333 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:28:42,481 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:28:42,560 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:29:05,334 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:29:05,409 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:29:42,567 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:29:42,617 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:30:05,412 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:30:05,472 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:30:42,619 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:30:42,679 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:31:05,473 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:31:05,533 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:31:42,686 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:31:42,732 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:32:05,542 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:32:05,598 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:32:42,733 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:32:42,782 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:33:05,600 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:33:05,661 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:33:42,787 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:33:42,837 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:34:05,663 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:34:05,712 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:34:42,839 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:34:42,892 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:35:05,713 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:35:05,761 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:35:42,895 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:35:42,942 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:36:05,762 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:36:05,810 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:36:42,943 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:36:42,993 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:37:05,811 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:37:05,880 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:37:43,001 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:37:43,048 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:38:05,885 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:38:05,944 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:38:43,051 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:38:43,120 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:39:05,946 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:39:05,994 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:39:43,123 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:39:43,168 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:40:43,171 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:40:43,219 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:41:43,221 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:41:43,271 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:42:43,273 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:42:43,343 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:43:43,345 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:43:43,399 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:44:43,407 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:44:43,460 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:45:43,465 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:45:43,529 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:46:43,531 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:46:43,584 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:47:43,590 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:47:43,630 - INFO - istemci - /heartbeat isteði baþarýyla gönderildi.
2025-09-23 16:48:43,635 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:48:53,649 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FD520>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
2025-09-23 16:49:53,651 - INFO - istemci - GIDEN ÝSTEK: /heartbeat
2025-09-23 16:50:03,661 - ERROR - istemci - /heartbeat isteði gönderilirken að hatasý oluþtu: HTTPConnectionPool(host='192.168.53.1', port=5432): Max retries exceeded with url: /heartbeat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A2090FC770>, 'Connection to 192.168.53.1 timed out. (connect timeout=10)'))
